### DISCUSSION TITLE
Leaflet not responding properly to resize events?

### DISCUSSION THREAD

**Discussion by llama-for3ver** [vue-leaflet/vue-leaflet#398] [Q&A]
I have some CSS that increases the size of a map's parent div:
```css
.map {
    width: 25vw;
    height: 25vh;
    transition: width 0.25s ease-out, height 0.5s ease-out;
}

.map:hover {
    width: 50vw;
    height: 50vh;
}
```

But when I hover over it, it doesn't load the rest of the tiles necessary:
Not hovering:
<img width="427" alt="image" src="https://github.com/user-attachments/assets/e7a487c3-d9fd-4d41-984c-e3a8d4132dab" />
Hovering:
<img width="843" alt="image" src="https://github.com/user-attachments/assets/57c3d45d-f309-4dd5-9257-a40971b39dcd" />
Even when I pan around, it doesn't seem to load all needed tiles. Am I approaching this wrong or do I need to do something special?
It also seems LPolyline is not liking it either.
