### ISSUE TITLE
Crash while running in dev mode in Vite

### ISSUE THREAD

**Issue by dumbasPL** [vue-leaflet/vue-leaflet#339]
## steps to reproduce

1. create an empty vue with javascript project with vite `yarn create vite`
2. install this package and the leaflet package
3. replace App.vue with:

```vue
<script setup>
import "leaflet/dist/leaflet.css";
import { LMap } from "@vue-leaflet/vue-leaflet";
import { ref } from "vue";

const zoom = ref(1);
</script>

<template>
  <div style="height:600px; width:800px">
    <l-map ref="map" v-model:zoom="zoom" :center="[0, 0]">
    </l-map>
  </div>
</template>
```

4. run the dev server with `yarn dev`
5. do to the website and observe the error: `TypeError: Cannot read properties of undefined (reading 'Default')`

If you build for production using (`yarn build && cd dist && npx serve`) then the map works correctly.

This problem seems to be nix* related because it seems to work fine when running on Windows.

## error screenshot

![image](https://github.com/vue-leaflet/vue-leaflet/assets/29180158/0c7241ce-38b0-474e-8e25-c58248fa7dc1)

## Versions
```yaml
os: Arch Linux, also tested and not working on Ubuntu
node: 18.16.0
vue: 3.3.4
vite: 4.4.5
leaflet: 1.9.4
vue-leaflet: 0.10.1
```
